version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
      - ./gradlew assembleDebug
